<?php

namespace AutovistaAppraisal;

class ApiException extends \Exception
{
	const APPRAISAL_ACTIVATION_FAILED = 'APPRAISAL_ACTIVATION_FAILED';
	const AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED';
	const IDENTIFICATION_FAILED = 'IDENTIFICATION_FAILED';
	const INCOMPLETE_PARAMETERS = 'INCOMPLETE_PARAMETERS';
	const REGNO_MISMATCH = 'REGNO_MISMATCH';
	const REGNO_REQUIRED = 'REGNO_REQUIRED';
	const SESSION_EXPIRED = 'SESSION_EXPIRED';
	const TRAFI_QUERY_TIMEOUT = 'TRAFI_QUERY_TIMEOUT';
	const UNKNOWN_QUERY_TYPE = 'UNKNOWN_QUERY_TYPE';
	const VALID_INTRAFFIC_DATE_REQUIRED = 'VALID_INTRAFFIC_DATE_REQUIRED';
	const VEHICLE_MISMATCH = 'VEHICLE_MISMATCH';
	const VEHICLE_NOT_REGISTERED = 'VEHICLE_NOT_REGISTERED';
}
